<?php

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="link authorization-link login-authorization" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <?php if($block->isLoggedIn()): ?>
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
            <?= /* @noEscape */ $dataPostParam ?>></span><span class="my-account"></span> <?= $escaper->escapeHtml($block->getLabel()) ?></a>
    <?php else: ?>

        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
            <?= /* @noEscape */ $dataPostParam ?>></span><span class="my-account"></span> <?= $escaper->escapeHtml($block->getLabel()) ?></a>
        <script>
            require([
                'jquery',
                'Magento_Customer/js/model/authentication-popup',
                'Magento_Customer/js/customer-data'
            ],function($,authenticationPopup,customerData){
                $(document).ready(function(){
                    $('.login-authorization').on('click',function(event){
                        var customer = customerData.get('customer');
                        if(!customer.firstname){

                            event.preventDefault();
                            authenticationPopup.showModal();
                            return false;
                        }
                        return true;
                    });
                });
            });
        </script>
    <?php endif; ?>
</li>
