<div class="notices-section">
    <div class="notices-content">
        <img src="<?php echo $block->getViewFileUrl('images/header/cards.png'); ?>" alt="Cards Image" class="cards-image" />
        <div class="notices-text">
            <p class="notices-title">3 cuotas sin interés con Banco Santander + Envío GRATIS en compras superiores a $0000</p>
        </div>
    </div>
    <img src="<?php echo $block->getViewFileUrl('images/header/Rectangle_14.svg'); ?>" alt="Decorative Line" class="decorative-line" />
</div>
