
<div class="block-sacsi-links">
    <ul class="sacsi-links">
        <li id="link-location">
            <?= $block->getChildHtml('sacsi_link_location'); ?>
        </li>
        <li id="link-account">
            <?= $block->getChildHtml('sacsi_link_micuenta'); ?>
        </li>
        <li id="link-cart">
            <?= $block->getChildHtml('sacsi_link_cart'); ?>
        </li>
    </ul>
</div>
