<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */
?>
<div>
    <a href="#"
       class="action tocompare myown-catalog-compare"
       title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
       aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
       data-post='<?= /* @noEscape */ $block->getCompareHelper()->getPostDataParams($block->getProduct()) ?>'
       role="button">
        <span class="compare-icon"><p>Comparar</p></span>
    </a>
</div>

